//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualizerExtension.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisualizerExtension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open volume mixer.
        /// </summary>
        public static string Action_OpenVolumeMixer {
            get {
                return ResourceManager.GetString("Action_OpenVolumeMixer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test visualizer.
        /// </summary>
        public static string Action_PlayTestSignal {
            get {
                return ResourceManager.GetString("Action_PlayTestSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play a tone ladder and sweep that lights every bar in turn.
        /// </summary>
        public static string Action_PlayTestSignal_Subtitle {
            get {
                return ResourceManager.GetString("Action_PlayTestSignal_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizer.
        /// </summary>
        public static string Band_Title {
            get {
                return ResourceManager.GetString("Band_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizer (braille).
        /// </summary>
        public static string Band_Title_Braille {
            get {
                return ResourceManager.GetString("Band_Title_Braille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizer (blocks + VU).
        /// </summary>
        public static string Band_Title_Vu {
            get {
                return ResourceManager.GetString("Band_Title_Vu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizer settings.
        /// </summary>
        public static string Command_Settings {
            get {
                return ResourceManager.GetString("Command_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change how the dedicated visualizer page looks.
        /// </summary>
        public static string Command_Settings_Subtitle {
            get {
                return ResourceManager.GetString("Command_Settings_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizer.
        /// </summary>
        public static string Command_Visualizer {
            get {
                return ResourceManager.GetString("Command_Visualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin the Visualizer band(s) via the Dock&apos;s band manager.
        /// </summary>
        public static string Command_Visualizer_Subtitle {
            get {
                return ResourceManager.GetString("Command_Visualizer_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a background extension for PowerToys Command Palette — there is nothing to launch directly. Open Command Palette and search for &quot;{1}&quot;, or pin the Visualizer band in the Dock..
        /// </summary>
        public static string DirectLaunch_Message {
            get {
                return ResourceManager.GetString("DirectLaunch_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizer for Command Palette.
        /// </summary>
        public static string Extension_DisplayName {
            get {
                return ResourceManager.GetString("Extension_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open visualizer.
        /// </summary>
        public static string Hub_OpenVisualizer {
            get {
                return ResourceManager.GetString("Hub_OpenVisualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical bars with peak caps.
        /// </summary>
        public static string Settings_PageStyle_Bars {
            get {
                return ResourceManager.GetString("Settings_PageStyle_Bars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizer page style.
        /// </summary>
        public static string Settings_PageStyle_Desc {
            get {
                return ResourceManager.GetString("Settings_PageStyle_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page style.
        /// </summary>
        public static string Settings_PageStyle_Label {
            get {
                return ResourceManager.GetString("Settings_PageStyle_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oscilloscope.
        /// </summary>
        public static string Settings_PageStyle_Oscilloscope {
            get {
                return ResourceManager.GetString("Settings_PageStyle_Oscilloscope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Hz.
        /// </summary>
        public static string Unit_Hz {
            get {
                return ResourceManager.GetString("Unit_Hz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kHz.
        /// </summary>
        public static string Unit_kHz {
            get {
                return ResourceManager.GetString("Unit_kHz", resourceCulture);
            }
        }
    }
}
